version: "3.8"
services:
  docker-mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=taskmanagerdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    restart: always

  docker-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    depends_on:
       - docker-mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/taskmanagerdb?autoReconnect=true&failOverReadOnly=false&maxReconnects=5
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user

